apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-ido
spec:
 containers:
 - name: redis-storage
   image: redis:alpine
   volumeMounts:
   - name: redis-persistant-storage
     mountPath: /data/redis
 volumes: 
 - name: redis-persistant-storage
   emptyDir: {}
      
    

  
