apiVersion: v1
kind: Service
metadata:
  name:  nginx-resolver-service
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      name: grpc
  type: NodePort
