apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app-deploy
spec:
  selector:
    matchLabels:
      app: hr-web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hr-web-app
    spec: 
      containers:
      - name: hr-web
        image: kodekloud/webapp-color
        ports:
          # - ContainerPort:
    

  
