apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
spec:
 containers:
 - name: static-busybox
   image: busybox
   command: ["sleep"]
   args: ["1000"]  
 nodeSelector:
   env: master
 tolerations:
 - operator: "Exists"
      
    

  
